; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:upesy_wroom]
platform = espressif32
board = upesy_wroom
framework = arduino
upload_port = COM6
monitor_port = COM6
upload_speed = 921600
monitor_speed = 115200
board_build.partitions = partitions.csv
board_build.filesystem = spiffs
lib_deps = 
	me-no-dev/AsyncTCP@^3.3.2
	me-no-dev/ESPAsyncWebServer@^3.6.0
	thingpulse/ESP8266 and ESP32 OLED driver for SSD1306 displays@^4.6.1
	kosme/arduinoFFT@^2.0.4
build_flags = 
	-DCORE_DEBUG_LEVEL=2
	-UCONFIG_BTDM_CTRL_MODE_BR_EDR_ONLY
	-DCONFIG_BTDM_CTRL_BR_EDR_MAX_ACT=1
	-DCONFIG_BT_CTRL_BR_EDR_MAX_ACL_CONN=1
	-DCONFIG_BTDM_CTRL_MODE=1
	-DCONFIG_BT_CTRL_COEX_PHY_CODED_TX_RX_TLIM=1
	-DCONFIG_BTDM_CTRL_STACK_POOL_SIZE=6000
	-DCONFIG_OPTIMIZATION_LEVEL=3
	-DCONFIG_HEAP_POISONING_DISABLED=1
	-DCONFIG_HEAP_TRACING_OFF=1
	-DCONFIG_ESP32_WIFI_TASK_PINNED_TO_CORE_1=1
	-DCONFIG_ESP32_WIFI_TASK_PINNED_TO_CORE=1
	-DCONFIG_EXTERNAL_COEX_ENABLE=1
	-DCONFIG_ESP32_WIFI_SW_COEXIST_ENABLE=1
	
	-Os
	-ffunction-sections
	-fdata-sections
	-Wl,--gc-sections
	-DNDEBUG
